CREATE DATABASE BOOK;
USE BOOK;
CREATE TABLE CHAPTER(
ID INT PRIMARY KEY,
NAME VARCHAR(20),
PAGES INT,
EMAIL VARCHAR(50));
INSERT INTO CHAPTER(ID,NAME,PAGES,EMAIL)
VALUES
(01,"X",24,"ABC"),
(02,"Y",26,"DEF"),
(03,"Z",28,"IJK");
-- VIEW DATA--
SELECT*FROM CHAPTER;
-- CHANGING DATA INSIDE THE TABLE--
UPDATE CHAPTER
SET PAGES=30
WHERE ID=02;
SELECT*FROM CHAPTER;
-- ADDING COLUMN TO THE TABLE WHICH WILL BE NULL INITAILLY--
ALTER TABLE CHAPTER
ADD CITY VARCHAR(50);
SELECT*FROM CHAPTER;
-- ADDING VALUE TO EACH ROW OF NEW COLUMN USING 3 DIFFRENET METHODS
UPDATE CHAPTER 
SET CITY="DELHI"
WHERE ID=01;

UPDATE CHAPTER 
SET CITY=
CASE
 WHEN ID=02 THEN "MUMBAI"
 WHEN ID=03 THEN "PUNE"
END
WHERE ID IN (2,3);
SELECT*FROM CHAPTER;
-- USING MODIFY CLAUSE THET IS USED FOR CHANGEING DATATYPE, SIZE CONSTRAUNTS--
ALTER TABLE CHAPTER
MODIFY NAME VARCHAR(40);
-- RENAMING COULMN AND MODIFYING JUST USING CHANGE CLAUSE--
ALTER TABLE CHAPTER
CHANGE NAME FULLNAME VARCHAR(50);
-- RENAMING THE TABLE--
ALTER TABLE CHAPTER
RENAME TO CHAPTERS;
-- RMOVING SEPECIIFIC DATA FROM THE TABLE--
DELETE FROM CHAPTERS
WHERE ID=03;
SELECT*FROM CHAPTERS;
-- DELETING ALL THE DATA FROM THE AND KEEPING THE STURTURE INTACT--
TRUNCATE TABLE CHAPTERS;
INSERT INTO CHAPTERS(ID,FULLNAME,PAGES,EMAIL,CITY)
VALUES
(01,"X",24,"ABC","A"),
(02,"Y",26,"DEF","B"),
(03,"Z",28,"IJK","C");
SELECT*FROM CHAPTERS;
-- DELETING WHOLE TABLE--
DROP TABLE CHAPTERS;
DROP DATABASE BOOK;


