REATE DATABASE DEPATMENT;
USE DEPATMENT;

CREATE TABLE COURSE(
CID INT PRIMARY KEY,
NAME VARCHAR(20));

INSERT INTO COURSE(CID,NAME)
VALUES
(01,"PYTHON"),
(02,"JAVA"),
(03,"SQL");

CREATE TABLE STUDENT(
SID INT PRIMARY KEY,
NAME VARCHAR(30),
CID INT,
FOREIGN KEY(CID) REFERENCES COURSE(CID)
ON UPDATE CASCADE
ON DELETE CASCADE);

INSERT INTO STUDENT(SID,NAME,CID)
VALUES
(21,"KIRAN",01),
(22,"SAM",02),
(23,"MAX",02),
(24,"BEN",03);

SELECT*FROM COURSE;
SELECT*FROM STUDENT;

UPDATE COURSE
SET CID=09
WHERE CID=02;

SELECT *FROM COURSE;
 
