-- inner join--
CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
S_ID INT PRIMARY KEY,
NAME VARCHAR(20));
INSERT INTO STUDENT(S_ID,NAME)
VALUES
(101,"ADAM"),
(102,"BOB"),
(103,"CASEY");

CREATE TABLE COURSE (
S_ID INT PRIMARY KEY,
COURSE VARCHAR(30));
INSERT INTO COURSE(S_ID,COURSE)
VALUES
(102,"ENGLISH"),
(105,"MATH"),
(103,"SCIENCE"),
(107,"CSE");

SELECT*FROM STUDENT;
SELECT*FROM COURSE;

SELECT*
FROM STUDENT
INNER JOIN COURSE
ON STUDENT.S_ID = COURSE.S_ID;
-- TO REMOVE THE DUPLICATE COLUMNS--
SELECT
STUDENT.S_ID,
STUDENT.NAME,
COURSE.COURSE
FROM STUDENT 
INNER JOIN COURSE
ON STUDENT.S_ID=COURSE.S_ID;

-- LEFT JOIN--
SELECT*
FROM STUDENT
LEFT JOIN COURSE
ON STUDENT.S_ID=COURSE.S_ID;

-- Right join --
SELECT *
FROM STUDENTS 
RIGHT JOIN COURSES
ON STUDENTS.S_ID=COURSSRS.S_ID;

-- FULL-JOIN: PROVIDES THE ALL RECORDS IT CONSIST OF RIGHT JOIN+UNION+LEFT JOIN
SELECT*
FROM STUDENT AS X
LEFT JOIN COURSE AS B
ON X.S_ID=B.S_ID
UNION
SELECT*
FROM STUDENT AS X
RIGHT JOIN COURSE AS B
ON X.S_ID=B.S_ID;
-- WITHOUT REPEATING COLUMN
SELECT 
    x.S_ID,
    x.NAME,
    b.COURSE
FROM STUDENT AS x
LEFT JOIN COURSE AS b
ON x.S_ID = b.S_ID
UNION
SELECT 
    x.S_ID,
    x.NAME,
    b.COURSE
FROM STUDENT AS x
RIGHT JOIN COURSE AS b
ON x.S_ID = b.S_ID;
